### PR TITLE
Light Image Updates

### PR DESCRIPTION
**Pull request by banksio**
- Changed BitmapScalingMode to HighQuality for light images to ensure 128px images scale down without jagged edges. 
image

- Updated the light images for:
-LCT001
-LCT002 (now 128px)

- Added new light images for:
+LCT007
+LCT010
+LCT011
+LCT014
+LTW001
+LTW011
+LWB006
+LWB007

- These light images now align with each other to produce a cleaner display of the lights in the Hue system. (All below are 128px)

### CODE REVIEW

**Comment by Hyrules** [comment]
Thanks. I will merge it with the dev branch which i'm currently working on.

**Comment by banksio** [comment]
No problem, I'm working on getting the rest of them done but that will take a while.

**Comment by Hyrules** [comment]
Take your time there is no hurry. This takes a lot of time and that part of the reason I never really done more of them. If you want to help me you are more than welcome. I normally work on the dev branch and when I do a release I merge the branches.

**Comment by banksio** [comment]
Thanks, that's good to know as I'd love to help. In the future I'll pull request to dev so you can then merge for a release as normal. 🙂

**Comment by Hyrules** [comment]
if you have suggestion as well to change some code or convert it to something more stable i'm open to suggestions. I'm still fighting sensor. I would like to create a class that's really generic for any kind of sensor and i'm currently running in circles.

**Comment by banksio** [comment]
Sure, I'm still learning C# but if I think I could improve anything I'll definitely have a tinker.

**Comment by banksio** [comment]
@Hyrules I'm struggling to get the current dev branch to build and start, does it work for you?

**Comment by Hyrules** [comment]
Working fine here what error do you have ?

**Comment by banksio** [comment]
This is what I get, maybe it's a problem with my fork?

image

**Comment by Hyrules** [comment]
ok there is a file missing. I will commit it when I get home in about 2 hours. I don't know why but sometimes my git plugin automatically ignores files I add to the solution. For the expression interaction missing you can try changing the setup of your visual studio to install blend which contains the expression dll but you don't need blend to code in WinHue. Just the expression. For the missing string I will take a look if something is missing when i'm home.

**Comment by banksio** [comment]
Ah OK thank you, I'll have a look at blend too - I've got it installed but not sure if its working or not.

**Comment by Hyrules** [comment]
you can try to pull the commit I have done for the UpdateManager file. Let me know if you still have the issues with the missing MainForm_Status... string.

**Comment by banksio** [comment]
Working well now, and blend seems to have sorted itself out. Thanks!

**Comment by Hyrules** [comment]
Nice to hear. As I said don't bother learning blend I don't use it. Just need Interactions dll for tyhe program. Makes some things easier.

**Comment by Hyrules** [comment]
Actually the Width but is not fixed. I just made it worse. I'll try to fix it asap. You might find out that the windows does not fill properly now.

**Comment by banksio** [comment]
Oh yeah I see what you mean. Hopefully it won't take long to fix!

**Pull request merged**
