### PR TITLE
Add support for archetype-based light images

### PR DESCRIPTION
**Pull request by banksio**
## Summary
+Added support for archetype-based light images.
+Added Hue Play light images.

## Detail
Since Philips have discontinued the [Supported lights](https://developers.meethue.com/develop/hue-api/supported-devices/#Supported-lights) table on their API docs, it is tricky to add new light images as the models are unknown. So I added code to check the archetype of each light and load images with the `archetype_` prefix (e.g. `archetype_huebloom_off`).

This should help get rid of any errors where the specific model ID of the same light has not been added to the light images folder, and also helps to keep the number of duplicate images down.

The model ID of each light is still checked before the archetype, so that specific light models can still be recognised. But now if an ID is unknown there is a higher chance of the correct image being loaded.

The only issue is that the `classicbulb` archetype is the default for all bulbs that the bridge doesn't know about. So for example, if there is an OSRAM bulb, then it would load the `classicbulb` archetype - which would be an image of a Hue White bulb. This would also be an issue if Philips update the bulbs' design -  a single archetype image would not cover all exact models. The only ways to get around this are to make sure there are always correct model images in the folder, or use less realistic images (such as silhouettes like the official app).

So, for now I've only done archetype images for the Hue Play, Bloom, Iris, Go, Lightstrip, Spot bulbs, and Flood bulbs, so it works exactly as it currently does. For the images, I used the latest model image, and left the old model images alone so they still work!

Also I've added images for the Hue Play because we didn't have any yet!

Hope you like what I've done, if not just let me know.

### CODE REVIEW

**Comment by Hyrules** [comment]
Perfect I'll take a look at this evening and give you some feedback.

**Comment by Hyrules** [comment]
By the way I don't know if you saw but I created a Project for WinHue. So people can see what is going on.

https://github.com/Hyrules/WinHue3/projects/1

**Comment by Hyrules** [comment]
Seems to be working very well. Good work and thanks alot.

**Comment by banksio** [comment]
Thanks, I'm glad you like it! Yeah I saw that project board - it's great to have a semi-official roadmap now on GitHub!

By the way, I noticed lately you've been changing a lot of the controls such as the watermark textbox and integerupdown. I was wondering if you could give me a sort of rundown of what you have changed since my efforts on theming have been going slow lately due to the custom controls like these (especially watermarktextbox). If you're not using them anymore then I won't bother to theme them because they're quite tricky to do so.

**Comment by Hyrules** [comment]
Everything that is from the Xceed toolkit watermark textbox, numeric up down and some timespan spinners  have been remove or will be remove. I'm tired of having the xceed toolkit as a dependency for the project as I have often hit bugs with their software that is already fix in the pro version and take 6 months to a year to be fixed in the community version. I have some doubt of my own about how they work with the code. As much as their toolkit is practical depending of someone else code and waiting to be fixed is a pain. I wouldn't say if they did fix it quickly but their release timeframe for community version is sometime 6 months or more which I find unacceptable. Most of the controls are replace with the standard version using behaviors. The only exception is the timespan spinner which is more complicated but you have acces to the source code for the control so you can theme is as you like.

**Comment by Hyrules** [comment]
Ok so now I have completely remove Xceed toolkit from the project as a dependency their latest release pissed me so no more. The move the DataGrid to the paying version of their plugin so now I can't use it the WinHue for the group and schedule views. I'm pretty sure they are making some bugs on purpose to force people to buy the pro version.

**Comment by banksio** [comment]
@Hyrules All is well in my opinion, never liked having to theme their stuff, most of it seems unnecessarily complicated. Let me know if I can help with theming any new controls etc.

**Comment by Hyrules** [comment]
If you have a few minutes to test the latest dev version a little on my side it seems to be working properly. I'm about to release it as the next release. Just let me know how it behave for you. I have added auto refresh of the objects every 3 seconds.

**Comment by banksio** [comment]
@Hyrules Sure, I've just given it a go. Unfortunately for me the app is now really quite laggy - in terms of things like mouse over and click responsiveness. But only in the windows which show the bridge objects like MainWindow or the Rule Creator for example (objects in the drop down).

Maybe it is the auto refresh but exaggerated because my laptop is a lot slower compared to your PC?

**Comment by Hyrules** [comment]
you can try disabling the timer in the mainform see if the lag occures ?
line 103 of the mainform method file comment the refresh timer start line.

**Comment by banksio** [comment]
@Hyrules Unfortunately that doesn't solve it.

**Comment by Hyrules** [comment]
There isn't any logging of any kind in the refresh item timer. You will still see when the bridge refreshed the view. Try the latest dev version. I have changed the timer to 30 seconds and made the refresh event async. It shouldn't block the main form.

**Comment by banksio** [comment]
@Hyrules Sorry, should've said, I just saw in the event log that it was reloading the light images. I will definitely try dev but it's half past midnight in the UK right now so will have to be tomorrow if that's OK!

**Comment by Hyrules** [comment]
don't worry about it. take your time. have a good night.

**Comment by banksio** [comment]
Unfortunately that hasn't fixed it. I'm really not sure now as to what is causing it.

**Comment by Hyrules** [comment]
It's really odd because i'm not having any kind of issue here. But my computer is really not a good gauge for that type of bug because it's a beast. Everything is rather smooth. I know that wpf relies on the graphic card alot so is it possible your drivers are not installed and you are running on microsoft basic drivers ?

**Comment by banksio** [comment]
Not that, it's definitely something with the build since I've got the current release installed and that's smooth as butter. I'm just trying to figure out why the light images won't load and see if that fixes it. Back when I added the archetype support I wasn't having any lag issues. 😕

**Comment by Hyrules** [comment]
You don't have any images loading ?

**Comment by banksio** [comment]
CPU goes to about 25% for a few seconds whenever I click a light. Memory is OK. Yes I'm on 2019 - maybe it is the problem.

Maybe you could send me an installer exe for the latest dev if it's easy to do? That way I don't have to compile or worry about the IDE at all and then I'll know if it's my problem or something with the build that won't run on my laptop.

**Comment by Hyrules** [comment]
actually I just made the installer to test myself.

[WinHue 3.0.4169.0 Setup.zip](https://github.com/Hyrules/WinHue/files/2998819/WinHue.3.0.4169.0.Setup.zip)

**Comment by Hyrules** [comment]
if you want you can try the profiler in Visual studio. it will tell you exactly what is happening and taking some cpu time. Debug -> Performance Profile when you are there click on Application Timeline, CPU usage and GPU Usage and press Start at the bottom. Play with the app by clicking a couple of objects and then click stop collection. It will show you the application timeline which tell you how long it takes to execute some stuff. Really cool stuff to optimize the code.

**Comment by Hyrules** [comment]
image

**Comment by banksio** [comment]
Alright just tried using the installer, got the same result. Gonna try what you said with the Performance Profile now...

**Comment by Hyrules** [comment]
I have a hunch. Try disabling the propertygrid... I'll tell you what to comment in a few.

**Comment by banksio** [comment]
Results are in... not sure if this tells you anything about your hunch on the propertygrid. I'm just jealous of how much screen real estate you have 😆 (this is taking up my whole 1366*768 laptop - still need a new one lol) 

Also there was no option for GPU in the Profiler, maybe because I'm on integrated?

image

**Comment by Hyrules** [comment]
yeah i have 3 4k monitors. It helps alot when coding. Can you save that diagsession and send it to me ? Just select the session and click File -> Save Report* as...

**Comment by Hyrules** [comment]
All I can say from this is that there something chocking the UI thread. I Have to find what.

**Comment by banksio** [comment]
Nice. Deleted the one in the screenshot as I just updated VS but this one is almost identical. Open WH>30 seconds clicking stuff>Close WH

[On OneDrive](https://1drv.ms/u/s!AgpAeg73FnuqgrsTCEXrxgMXQJyIEw).

Sorry for the delay there, had to upload it to OneDrive because of the size limit on GitHub.

**Comment by Hyrules** [comment]
Got it thanks. Oh... god.... something is really chocking the UI Thread something with the layout of the whole thing. 71% of the app is runtime is doing the layout. That's basically locking the UI thread causing the lag.

**Comment by banksio** [comment]
>71% of the app is runtime is doing the layout.

Yeah, that's basically how it feels when it runs, like a game at 1 FPS. But no idea what's causing it.

**Comment by Hyrules** [comment]
I can't actually see what is happening from your profiler session you can try to go in the CPU Usage tab (in the profile window) and look around. You will see what functions is use most of the cpu time. You can also click on it and see where in the code this happens. You can click on it and you will see the code like this

image

I'm singing off for tonight. I'll try to find more tomorrow. If you find something just let me know.

**Comment by banksio** [comment]
Looks good, yeah I'll have a look tomorrow and tell you what I find.

**Comment by banksio** [comment]
Moved issue to #224

**Pull request merged**
