### PR TITLE
Webpage Updates and Bug Fixes

### PR DESCRIPTION
**Pull request by banksio**
I've fixed all the bugs I could find so now the buttons and the new footer behave properly across all screen sizes. The title is also larger on desktop screen sizes.

- New: Modal for the changelog of the latest release, and size and downloads.
- New: Modal for selecting which download to be used when downloading the source code.

### CODE REVIEW

**Comment by banksio** [comment]
Seems to be an issue with the changelog formatting I've just realised after merge but not too major. @Hyrules thanks for the repository invite btw!

**Comment by Hyrules** [comment]
thanks to you. I think you can do merge now not sure though. No problem you can do another merge if you want.

**Comment by banksio** [comment]
@Hyrules Yep, I just committed a small bugfix directly, so it works! I'll fix the changelog formatting later as that seems to be a bit more in-depth.

**Comment by Hyrules** [comment]
nice !

**Pull request merged**
