### PR TITLE
Fluent Ribbon Changes

### PR DESCRIPTION
**Pull request by banksio**
- New icons for Refresh View and Bridge Settings (what do you think?)
- Changed `RibbonButton`s to `fluent:Button`s, as with other Fluent Ribbon components.
- Ribbon items now compress down so no scrollbar appears at smaller window sizes.
- New tab in menu for _Help_, maybe to replace _Help_ tab in ribbon to make the program more in line with how Office and other programs place the help menu.

I have tested everything I could think to test, including the sorting combobox - it does seem to work for me but I don't know if I've done it right!

### CODE REVIEW

**Comment by Hyrules** [comment]
Thanks everything seems to be fine on my side. Nice icons by the way ! fluent button is better than ribbon button. the fact that they were not highlighting was starting tu bug me thanks for fixing this.

**Comment by banksio** [comment]
@Hyrules Nice. Glad you like the icons! The ribbon icons not highlighting was bugging me too haha. Good job on getting mahapps removed so quickly, just one thing though - now that the themeengine or whatever it was is removed we won't be able to use that in case of an upgrade to fluent ribbon V6. I think it would be good option to stick with a ribbon but there is always possibility of redesigning the whole interface so we could make a completely custom theme engine? I don't know how tricky this would be though am up to the challenge. I have kind of an idea, could do a quick concept tomorrow.

**Comment by Hyrules** [comment]
I'm not sure how to make a theming engine at this time I don't think it's quite hard. Probably create a default color theme in the App.xml file and change the color with the code. You would have to bind elements of the theme to that static ressource. I think it's possible to create custom themes with fluent ribbon. they seem to use the same technology as mahapps. Go ahead for the concept i'm curious on what you have in mind. My imagination is not good when creating visual interface. I'm good a coding but not styling.

**Comment by banksio** [comment]
@Hyrules Oh I may have been thinking of a different thing with the fluent styling actually you are right. I take inspiration from other programs to get ideas usually. I'll make a few mock ups as it would be hard to redesign the UI without dumbing down the program but I don't want to do that as I think the essence of WinHue is how powerful it is. I think you are right on the theming engine, I read somewhere they might have to be DynamicResources or else they won't update at runtime. I'm quite good at VB but completely new to C and WPF so it is a learning experience for me but the xaml is similar to html so I find that easier.

**Comment by Hyrules** [comment]
you will see that C# is somewhat familiar to VB. Sure there are some significant differences but if you use the .net framework the commands basically stays the same. Most likely right for DynamicResource. I will take a look at that sometime. I still have stuff i'd like to implement like : 

- LIFX support (have 2 of them)
- Animation for WinHue (play a sequence of light color and brightness stuff like that)
- Schedule can modify sensors (it seems possible from what i had with some issues here)

Maybe not in that order but it's in my head.

**Pull request merged**
