### PR TITLE
Light Image Updates, String Corrections

### PR DESCRIPTION
**Pull request by banksio**
**1. All Philips Hue light bulbs now have an image, and images are now 128px! 🎉** 

**2. Updated Hue light group image for light groups. (Also ribbon icon)**

**3. Updated default light image.**

**4. Corrected some strings in `GlobalStrings.resx`.**

**-The ribbon icons for groups looks ugly, I am researching a way to fix this.**

Added light images for:
+LCT012 (Colour Candle)
+LTW012 (White Ambiance Candle)
+LTW013 (White Ambiance GU10)
+LTW014 (" ")
+LTW004 (White Ambiance A19)
+LTW010 (" ")
+LTW015 (" ")
-LLC006 (LivingColours Gen3 Iris)

Updated light images for:
-LCT003
-LLC007
-LLC010
-LLC013
-LWB004

Removed light images for LLC001 - this light cannot actually be connected to the Hue Bridge.

### CODE REVIEW

**Comment by Hyrules** [comment]
Mergin is done. Thanks

**Comment by banksio** [comment]
Great, thanks

**Comment by Hyrules** [comment]
If you have other ideas don't hesitate.

**Comment by banksio** [comment]
@Hyrules Sure, thanks for letting me know! I'll be most active at weekends as I'm a little busy on weekdays, and I'll definitely ask you if I need anything as I am new to C# and WPF.

**Comment by Hyrules** [comment]
Do you have any idea for some icons for the Lightstrip and the bloom ? There look kinda out of phase with the other icons now :)

**Comment by banksio** [comment]
I agree, I have been thinking about the lightstrips but they don't really have images that I can use easily. I am working on the Bloom though. The thing is, most bulbs have an image with a transparent background on some website, but I haven't found one yet for the lightstrips. 🤔

**Comment by Hyrules** [comment]
Do you have photoshop ?
3285784_ra

**Comment by Hyrules** [comment]
[3285784_ra.zip](https://github.com/Hyrules/WinHue3/files/1286256/3285784_ra.zip)

**Comment by Hyrules** [comment]
This is the PSD for the bloom.

**Comment by banksio** [comment]
No, but I'm using GIMP which I'm quite familiar with.On 7 Sep 2017 23:15, Hyrules <notifications@github.com> wrote:Do you have photoshop ?

**Comment by Hyrules** [comment]
I think it can open the psd's from photoshop.

**Comment by banksio** [comment]
Ah thanks, I'll make sure to send you my project files once I'm done too.

**Comment by Hyrules** [comment]
Otherwise I can give you a tiff. Let met know.

**Comment by banksio** [comment]
Yeah, I think you're right. I'll check tomorrow evening.

**Comment by banksio** [comment]
Hey @Hyrules,
I was wondering if you could tell me where the code is located that controls if a light group displays as on or off (under groups), I'm experimenting with some changes to the way they're displayed.

Thanks!

P.S. PSD opens fine

**Comment by Hyrules** [comment]
Utils->HueObjectHelper->Line:867 you have the GetImageForLight
After that you can find the references for that function.

**Comment by banksio** [comment]
Thanks, I was trying to make it so that if 1/3 of the lights in a group are on, one bulb will light, up to 100% of the lights being on, where all the bulbs will light up. I think it's either the group is on or the group is off, however?

e.g. 33% of lights on in group:
image

**Comment by Hyrules** [comment]
Nice ! For the groups the image are set in function at line 208.

**Comment by banksio** [comment]
@Hyrules thanks! The issue is though, that it only reports if the **whole group** is on or off.
`kvp.Value.Image = GDIManager.CreateImageSourceFromImage(kvp.Value.action.on.GetValueOrDefault() ? Properties.Resources.HueGroupOn_Large : Properties.Resources.HueGroupOff_Large);`

Do you know how I can find how many lights are on within the specific group?

**Comment by Hyrules** [comment]
kvp.value.lights gives you the list in the group unfortunately you cannot know with the actual group if the lights are on beside pooling each lights. There is however kvp.value.state.any_on or all_on you could use.

**Comment by banksio** [comment]
Ah OK, I think that will work. If I wanted to get the state of each light using the IDs however, would that be possible? I'm just wondering but I expect it would be too much work for a small feature.

**Comment by Hyrules** [comment]
You would have to call the bridge n (amount if lights in the group) amount of time to get the the state of each lights in the group. The question is does are the call worth it ? Will it slow things up ? My suggestion would be to use any_on and all_on. if any on true and all_on false you could light 1 or 2 bulb. This way you save calls to the bridge and chances things go wrong.

**Comment by banksio** [comment]
You're right; that's likely what I'll do but I'll have a play around tomorrow. As you said we don't want to keep calling the bridge. Also I've got new images for the bloom, lightstrip and lightstrip plus, I'll pull request once I've got the groups sorted!

**Pull request merged**
