### PR TITLE
Updated Bloom, Lightstrip and group images. Misc. cleanup.

### PR DESCRIPTION
**Pull request by banksio**
**Updated light images for:**
-LLC011 and 012.
-LST001 and 002.
-Groups (now shows some bulbs lit rather than just all or nothing).

**Bug fixes:**
-Removed obsolete resources and ensured btnScene is no longer referencing scenelarge.png, which has been deleted.

### CODE REVIEW

**Comment by banksio** [comment]
@Hyrules, I was trying to get it so that the main view refreshes when a light is toggled (so that the group image updates). However, I couldn't find a way to do this. Do you know a way? Thanks

**Comment by Hyrules** [comment]
You could try triggering a full refresh but that would cost a call to the bridge. Or try finding the groups in which the light is and update the image.

**Comment by Hyrules** [comment]
Nice job on the icons by the way !

**Comment by banksio** [comment]
Thanks! I tried to trigger a full refresh but couldn't see how to do it in the same action as the Toggle function. I didn't know what function to call to refresh. I don't really want to call the bridge again though, how would I be able to check which groups it affects locally?

**Comment by Hyrules** [comment]
MainFormViewModel_Methods line 172.

**Comment by banksio** [comment]
Thanks, I'll try and have a look when I get a chance.On 10 Sep 2017 21:43, Hyrules <notifications@github.com> wrote:MainFormViewModel_Methods line 172.

**Comment by Hyrules** [comment]
I think I have solved the most part of the issues involving any objects. The ExpandoObject I was talking about actually works pretty well. With this object I don't have to create any fixed class like lights or groups or sensors. I just deserialize any object into an expandoobject and add properties on the fly as needed. I have created an experimental branch on which I will work while I'm trying to convert most part of the code to expandoobject and will pull to the dev branch once fully tester and functionnal. Since this will take some time I don't expect to release any version soon. Just a heads up.

**Comment by banksio** [comment]
@Hyrules OK, I think I get the gist of it. Good luck on converting, hopefully it doesn't turn out to be too difficult! Thanks for the heads up on the version schedule. If there's anything I can test at any point for you please let me know.

**Comment by Hyrules** [comment]
this is actually easier than anticipated. I just have to remove all the casting. This is really incredible. This will remove alot of code casting and checks. I will never have to add new properties to objects again. ExpandoObject act as a javascript object which is typeless in in itself. Normally in C# you have to have a type if you want to add a property to a class you have to add it to the class and recompile. Not with an this. you just have to do myobject.property = what you want. this automatically add a property and the value. This is also valid for methods and events. The only part not working right now is the propertygrid since an expandoobject is not like a typical class where you have a definition you actually have to tell the object and property grid how to handle when added to a propertygrid. But this is much less code that having to create every types for lights and sensors and all. If you want to look at the code you can try to pull the experimental build. Beware i'm not finished converting so stuff might crash but the light toggling of the light and grousp works.

**Comment by Hyrules** [comment]
Basically yes. I just take the json from the bridge and deserialize it as an expando object. The end result is an object with all properties of a bridge object. I have read on the subject yesterday and the expandoobject can often cover 90% of the needs and if not there is also the dynamicobject which is a partially implemented expandoobject that you can have more control over it. For the property grid it normally reflect the object and get the properties but since an expandoobject is basically a fancy IDictionary<string,object> the property grid does not know how to handle it. So you have to create a typedescriptor which will as the name say describe the type to the property grid. I might have to go from expando to dynamicobject if I cannot get the type descriptor to work as intended. At the moment I can get the propertygrid to show root properties of an expando but if there are nested expando like the state of a light it just says that it's an expando without show the properties inside.

**Comment by banksio** [comment]
@Hyrules I think your GitHub plugin may have missed a file again, or am i just being dumb‽
image

**Comment by Hyrules** [comment]
Yes I still don't understand why some files get ignore when I create them but I just committed the file.

**Comment by banksio** [comment]
@Hyrules Cool thanks. Do you use the official GitHub plugin for Visual Studio? I do and that's worked well for me.

**Comment by Hyrules** [comment]
yes I'm using it but something is ignoring certain new files.

**Comment by Hyrules** [comment]
well after playing a while with expando and custom dynamic object I can say that they are pretty impressive but not for WinHue. The more I made modifications to the experimental branch the more I was finding it inconvenient. For example the whole getting the properties of an non existing object was virtually impossible so all the functionalities using Type.getproperties where not working so I couldn't prefill some boxes with properties. So I will most likely stay with strong types for now adding missing properties as needed.

**Comment by banksio** [comment]
@Hyrules Ah OK, that's interesting. Are there any issues that you haven't been able to solve with the old style objects?

**Comment by Hyrules** [comment]
Not at the moment. I found a way to have sensors working I think. Now i'm trying to display some of the class properties in the propertygrid properly. If you feel like helping there are a couple of addons I have been starting but not finishing like a clapper or an animation creator I would like to add at some point. Clapper is almost working but need some fine tuning or maybe a complete rewrite not sure there. If you have other ideas feel free to pitch them here.

**Comment by banksio** [comment]
@Hyrules That's good. I would help with what I can but unfortunately I don't know much C# yet! I'm also kinda busy at the moment so that's why I haven't done much. If the clapper is almost done I could have a look.

**Pull request merged**
